apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sriov-operator-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: online-sriov-clusters
        requeueAfterSeconds: 10
  template:
    metadata:
      name: 'sriov-{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/jnunyez/vse-carslab-managed'
        targetRevision: openshift-sriov-network-operator-updates
        path: 'components/apps/openshift-sriov-network-operator/overlays/default'
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
