---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: online-sriov-clusters
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          sriov-tests: "True"
